modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]] #mandatory
modId="cutewords" #mandatory
version="1.20.1-1.0.0" #mandatory
displayName="Cute Words: Chat Replacer" #mandatory
authors="Rinko1231" #optional
description="Replace player chat content according to the predefined config files"

[[dependencies.cutewords]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.cutewords]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
